<a href="https://colab.research.google.com/github/PraDeePP30/Scrapping_Basics/blob/main/extract_csv_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
pd.read_csv('https://www.football-data.co.uk/new/BRA.csv')

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,PH,PD,PA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
0,Brazil,Serie A,2012,19/05/2012,22:30,Palmeiras,Portuguesa,1.0,1.0,D,1.75,3.86,5.25,1.76,3.87,5.31,1.69,3.50,4.90
1,Brazil,Serie A,2012,19/05/2012,22:30,Sport Recife,Flamengo RJ,1.0,1.0,D,2.83,3.39,2.68,2.83,3.42,2.70,2.59,3.23,2.58
2,Brazil,Serie A,2012,20/05/2012,01:00,Figueirense,Nautico,2.0,1.0,H,1.60,4.04,6.72,1.67,4.05,7.22,1.59,3.67,5.64
3,Brazil,Serie A,2012,20/05/2012,20:00,Botafogo RJ,Sao Paulo,4.0,2.0,H,2.49,3.35,3.15,2.49,3.39,3.15,2.35,3.26,2.84
4,Brazil,Serie A,2012,20/05/2012,20:00,Corinthians,Fluminense,0.0,1.0,A,1.96,3.53,4.41,1.96,3.53,4.41,1.89,3.33,3.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4005,Brazil,Serie A,2022,07/08/2022,20:00,Fluminense,Cuiaba,1.0,0.0,H,1.49,4.01,8.38,1.54,4.01,9.20,1.51,3.80,7.60
4006,Brazil,Serie A,2022,07/08/2022,20:00,Palmeiras,Goias,3.0,0.0,H,1.26,6.26,11.25,1.29,6.50,13.00,1.24,5.99,11.21
4007,Brazil,Serie A,2022,07/08/2022,22:00,Fortaleza,Internacional,3.0,0.0,H,1.74,3.76,5.08,1.90,3.76,5.40,1.76,3.58,4.78
4008,Brazil,Serie A,2022,07/08/2022,23:00,Atletico-MG,Athletico-PR,2.0,3.0,A,1.51,4.18,7.32,1.58,4.40,7.70,1.50,4.04,7.01
4009,Brazil,Serie A,2022,09/08/2022,00:00,Coritiba,Santos,1.0,2.0,A,2.71,3.06,2.97,2.76,3.17,3.01,2.64,3.00,2.88